# Generated by Django 4.0.4 on 2022-04-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
