# Generated by Django 4.0.4 on 2022-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp1', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='siteusers',
        ),
    ]
