# Generated by Django 4.0.4 on 2022-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp1', '0003_rename_user_siteusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(max_length=5)),
                ('sugar', models.CharField(max_length=5)),
                ('chole', models.CharField(max_length=5)),
                ('bmi', models.CharField(max_length=5)),
                ('smoke', models.CharField(max_length=3)),
                ('drink', models.CharField(max_length=3)),
            ],
        ),
    ]
